'use client';
import React,{useEffect,useState,useRef} from 'react';
import gsap from 'gsap';
import {ScrollTrigger} from 'gsap/ScrollTrigger';
import desktop from './content/desktop.json';
import mobile from './content/mobile.json';
import intermediate from './content/intermediate.json';
import faq from './content/faq.json';
import menuOpen from './content/menu-open.json';
import {springTransition} from './spring';
import {cubicBezier} from './bezier';
import motion from './content/motion.json';
import Shader from './shader';
gsap.registerPlugin(ScrollTrigger);
function styleObject(text=''){return Object.fromEntries(text.split(';').filter(Boolean).map(line=>{const i=line.indexOf(':');if(i<0)return null;const k=line.slice(0,i).trim(),v=line.slice(i+1).trim();return [k.startsWith('--')?k:k.replace(/-([a-z])/g,(_,c)=>c.toUpperCase()),v]}).filter(Boolean))}
const aliases={class:'className',for:'htmlFor',tabindex:'tabIndex',viewbox:'viewBox',preserveaspectratio:'preserveAspectRatio',srcset:'srcSet',crossorigin:'crossOrigin',strokeWidth:'strokeWidth','stroke-width':'strokeWidth','stroke-linecap':'strokeLinecap','stroke-linejoin':'strokeLinejoin','fill-rule':'fillRule','clip-rule':'clipRule'};
function props(attrs={}){const p={};for(const [key,value]of Object.entries(attrs)){if(key==='href'&&value.startsWith('./#'))p.href=value.slice(2);else if(key==='style')p.style=styleObject(value);else if(key==='srcset')p.srcSet=value;else if(key==='autoplay')p.autoPlay=true;else if(['muted','loop','playsinline','controls'].includes(key))p[key==='playsinline'?'playsInline':key]=true;else if(key==='width'||key==='height')p[key]=value;else p[aliases[key]||(!key.startsWith('data-')&&!key.startsWith('aria-')?key.replace(/-([a-z])/g,(_,c)=>c.toUpperCase()):key)]=value}return p}
function textContent(node){return typeof node==='string'?node:(node.children||[]).map(textContent).join('')}
function findNode(node,test){if(typeof node==='string')return null;if(test(node))return node;for(const child of node.children||[]){const found=findNode(child,test);if(found)return found}return null}
const answerTemplate=findNode(desktop.sections[6].nodes[0],n=>n.attrs?.['data-pf-name']==='Answer');
function answerNode(answer){const clone=JSON.parse(JSON.stringify(answerTemplate));const paragraph=findNode(clone,n=>n.tag==='p');if(paragraph)paragraph.children=[answer];return clone}
function Accordion({node}){const [open,setOpen]=useState(node.attrs['data-pf-name']==='Open');const ref=useRef(null);const question=node.children.find(n=>n.attrs?.['data-pf-name']==='Question');const entry=faq.find(e=>e.question===textContent(question));const p=props(node.attrs);p.className=p.className.replace(/pf-v-(?:gger85|1svnqje)/,'pf-v-'+(open?'1svnqje':'gger85'));const toggle=()=>{const old=ref.current.getBoundingClientRect().height;setOpen(!open);requestAnimationFrame(()=>{const el=ref.current,end=el.getBoundingClientRect().height;gsap.fromTo(el,{height:old},{height:end,duration:.2,ease:cubicBezier(.44,0,.56,1),clearProps:'height'});ScrollTrigger.refresh()})};return <div {...p} ref={ref}><div {...props(question.attrs)} role="button" tabIndex={0} aria-expanded={open} onClick={toggle} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();toggle()}}}><Nodes nodes={question.children}/></div>{open&&entry&&<Node node={answerNode(entry.answer)}/>}</div>}
function Carousel({node}){const ref=useRef(null);useEffect(()=>{const el=ref.current,list=el.querySelector('ul'),previous=el.querySelector('[aria-label="Previous"]'),next=el.querySelector('[aria-label="Next"]');if(!list||!previous||!next)return;const update=()=>{for(const [button,disabled]of [[previous,list.scrollLeft<2],[next,list.scrollLeft>=list.scrollWidth-list.clientWidth-2]]){button.disabled=disabled;button.style.opacity=disabled?'0':'1';button.style.pointerEvents=disabled?'none':'auto'}for(const item of list.children){const r=item.getBoundingClientRect(),p=list.getBoundingClientRect();item.setAttribute('aria-hidden',r.right<=p.left||r.left>=p.right?'true':'false')}};const move=direction=>{const item=list.firstElementChild;gsap.to(list,{scrollLeft:Math.max(0,Math.min(list.scrollWidth-list.clientWidth,list.scrollLeft+direction*(item.getBoundingClientRect().width+10))),duration:.5,ease:'power3.out',onUpdate:update})};const back=()=>move(-1),forward=()=>move(1);previous.addEventListener('click',back);next.addEventListener('click',forward);list.addEventListener('scroll',update);update();return()=>{previous.removeEventListener('click',back);next.removeEventListener('click',forward);list.removeEventListener('scroll',update);gsap.killTweensOf(list)}},[node]);return <div {...props(node.attrs)} ref={ref}><Nodes nodes={node.children}/></div>}
function Project({node}){const ref=useRef(null);const hover=active=>{const el=ref.current,noButton=node.attrs['data-pf-name']==='no button';gsap.to(el,{filter:active?'grayscale(0)':'grayscale(1)',duration:.4});gsap.to(el.querySelector('[data-pf-name="Image"]'),{scale:active&&!noButton?1.1:1,duration:.4,ease:cubicBezier(.44,0,.56,1)})};return <a {...props(node.attrs)} ref={ref} onMouseEnter={()=>hover(true)} onMouseLeave={()=>hover(false)} onFocus={()=>hover(true)} onBlur={()=>hover(false)}><Nodes nodes={node.children}/></a>}
function Navigation({nodes}){const[open,setOpen]=useState(false);const previousOpen=useRef(false);const ref=useRef(null);useEffect(()=>{setOpen(false)},[nodes]);useEffect(()=>{const el=ref.current,icon=el.querySelector('[data-pf-name="Mobile Menu Icon"]');if(!icon)return;icon.setAttribute('role','button');icon.setAttribute('tabindex','0');icon.setAttribute('aria-label',open?'Close navigation':'Open navigation');icon.setAttribute('aria-expanded',String(open));const click=()=>setOpen(v=>!v),key=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();click()}};const close=e=>{if(e.target.closest('a'))setOpen(false)};icon.addEventListener('click',click);icon.addEventListener('keydown',key);el.addEventListener('click',close);const header=el.querySelector('header');if(previousOpen.current!==open)gsap.fromTo(header,{height:open?72:480},{height:open?480:72,duration:.4,ease:cubicBezier(.44,0,.56,1),clearProps:'height'});previousOpen.current=open;return()=>{icon.removeEventListener('click',click);icon.removeEventListener('keydown',key);el.removeEventListener('click',close);gsap.killTweensOf(header)}},[open,nodes]);return <div ref={ref} style={{display:'contents'}}><Nodes nodes={open?menuOpen:nodes}/></div>}
function Ticker({node}){const ref=useRef(null);useEffect(()=>{const el=ref.current;if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const reviews=textContent(node).includes('Richards Johnson'),logos=!textContent(node).trim(),count=reviews?4:logos?5:8,speed=reviews?(innerWidth<810?50:100):logos?50:60;const items=[...el.children];if(!items[count])return;const distance=items[count].offsetLeft-items[0].offsetLeft;const right=!!props(node.attrs).style.left;gsap.set(el,{x:0});const tween=gsap.to(el,{x:right?distance:-distance,duration:distance/speed,ease:'none',repeat:-1,paused:true});const observer=new IntersectionObserver(entries=>{entries[0].isIntersecting?tween.play():tween.pause()});observer.observe(el.parentElement);const enter=()=>tween.timeScale(reviews?.5:1),leave=()=>tween.timeScale(1);el.addEventListener('mouseenter',enter);el.addEventListener('mouseleave',leave);return()=>{observer.disconnect();tween.kill();el.removeEventListener('mouseenter',enter);el.removeEventListener('mouseleave',leave)}},[node]);return <ul {...props(node.attrs)} ref={ref}><Nodes nodes={node.children}/></ul>}
function Node({node}){if(typeof node==='string')return node;const p=props(node.attrs);if(node.tag==='shader')return <Shader {...p}/>;if(p.className?.split(' ').includes('pf-caRRT'))return <GlowButton node={node}/>;if(p.className?.split(' ').includes('pf-6o1HC'))return <Accordion node={node}/>;if(p.className==='pf-1ineur-container')return <Carousel node={node}/>;if(node.tag==='ul'&&p.style?.maxWidth==='100%'&&p.style?.listStyleType==='none')return <Ticker node={node}/>;if(node.tag==='a'&&p.className?.split(' ').includes('pf-eDUaF'))return <Project node={node}/>;const children=node.children?.map((n,i)=><Node key={i} node={n}/>);return React.createElement(node.tag,p,...(children||[]))}
function Nodes({nodes}){return nodes?.map((node,i)=><Node key={i} node={node}/>)}
function GlowButton({node}){const ref=useRef(null);const hover=active=>{const el=ref.current;gsap.to(el.querySelector('.pf-1l7inir'),{boxShadow:active?'0px 1px 7px 0px rgba(255,255,255,.24)':'0px 1px 9px 0px rgba(255,255,255,0)',duration:.3});gsap.to(el.querySelector('.pf-1mp9oxt'),{opacity:active?.5:.41,duration:.3});gsap.to(el.querySelector('.pf-1cwzqq7'),{background:active?'radial-gradient(50% 50% at 50% 50%, rgb(194,194,194) 0%, rgba(0,0,0,0) 100%)':'radial-gradient(50% 50% at 50% 50%, rgb(115,115,115) 0%, rgba(0,0,0,0) 100%)',duration:.3})};return React.createElement(node.tag,{...props(node.attrs),ref,onMouseEnter:()=>hover(true),onMouseLeave:()=>hover(false),onFocus:()=>hover(true),onBlur:()=>hover(false)},<Nodes nodes={node.children}/>)}
export default function Portfolio(){const [data,setData]=useState(desktop);const root=useRef(null);
 useEffect(()=>{const update=()=>setData(innerWidth<810?mobile:innerWidth<1200?intermediate:desktop);update();window.addEventListener('resize',update);return()=>window.removeEventListener('resize',update)},[]);
 useEffect(()=>{if(!root.current)return;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const context=gsap.context(()=>{if(reduced)return;
  const words=root.current.querySelectorAll('.pf-1wqlnff h1 span[style]');gsap.fromTo(words,{opacity:.001,y:10,filter:'blur(10px)'},{opacity:1,y:0,filter:'blur(0px)',...springTransition({type:'spring',damping:100,stiffness:400,mass:1}),delay:.5,stagger:.05,clearProps:'transform,opacity,filter'});
  const description=root.current.querySelectorAll('.pf-14oc2jn p span[style]');gsap.fromTo(description,{opacity:.001,y:5,filter:'blur(2px)'},{opacity:1,y:0,filter:'blur(0px)',...springTransition({type:'spring',damping:100,stiffness:400,mass:1}),delay:.7,stagger:.05,clearProps:'transform,opacity,filter'});
  root.current.querySelectorAll('.pf-nSE2Y,.pf-d6CNX').forEach(el=>gsap.fromTo(el,{opacity:0,x:-50},{opacity:1,x:0,...springTransition({type:'spring',damping:25,stiffness:127,mass:1}),delay:el.classList.contains('pf-d6CNX')?.45:.1,scrollTrigger:{trigger:el,start:'top bottom',once:true},clearProps:'transform,opacity'}));
  const wall=root.current.querySelector('.pf-bpslow');if(wall&&innerWidth>=810)gsap.fromTo(wall,{scale:.88},{scale:1,duration:.4,ease:cubicBezier(.44,0,.56,1),scrollTrigger:{trigger:wall,start:'top 50%',once:true},clearProps:'transform'});
  const footer=root.current.querySelector('footer');if(footer&&innerWidth>=810)gsap.fromTo(footer,{y:-500},{y:0,ease:'none',scrollTrigger:{trigger:footer.parentElement.parentElement,start:'top bottom',end:'bottom bottom',scrub:true}});
  const cue=root.current.querySelector('.pf-d3pyfu-container');if(cue)gsap.fromTo(cue,{y:0},{y:10,duration:2,repeat:-1,yoyo:true,ease:'none'});
  root.current.querySelectorAll('[data-pf-appear-id]').forEach(el=>{const id=el.dataset.pfAppearId,entry=motion[id];const breakpoint=innerWidth<810?'bf22ba':innerWidth<1200?'10hqf1j':'default';const spec=entry?.[breakpoint]===null?null:entry?.[breakpoint]||entry?.default;if(!spec)return;const t=spec.animate.transition||{};const initial={opacity:spec.initial.opacity,x:spec.initial.x,y:spec.initial.y,scale:spec.initial.scale};gsap.fromTo(el,initial,{opacity:1,x:0,y:0,scale:1,...springTransition(t),delay:t.delay||0,scrollTrigger:el.getBoundingClientRect().top>innerHeight?{trigger:el,start:'top 92%',once:true}:undefined,clearProps:'transform,opacity'});});
 },root);return()=>context.revert()},[data]);
 return <main ref={root} id="main" className="min-h-screen w-full"><div {...props(data.root[0])}><Navigation nodes={data.nav}/><div {...props(data.root[1])}><Nodes nodes={data.sections.flatMap(s=>s.nodes)}/></div><Nodes nodes={data.footer}/></div><div className="portfolio-sprites"><Nodes nodes={data.sprites}/></div></main>
}
